In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [3]:
df_customer=pd.read_csv("customer.csv")
df_customer

,Customer Id,Customer Fname,Customer Lname,Customer Country,Customer City,Customer State
0,20755,Cally,Holloway,Puerto Rico,Caguas,PR
1,19492,Irene,Luna,Puerto Rico,Caguas,PR
2,19491,Gillian,Maldonado,EE. UU.,San Jose,CA
3,19490,Tana,Tate,EE. UU.,Los Angeles,CA
4,19489,Orli,Hendricks,Puerto Rico,Caguas,PR
...,...,...,...,...,...,...
20647,18586,Diana,Tran,Puerto Rico,Caguas,PR
20648,16322,Anika,Davenport,Puerto Rico,Caguas,PR
20649,18579,Yuri,Smith,Puerto Rico,Caguas,PR
20650,16244,Hyacinth,Witt,Puerto Rico,Caguas,PR
20651,2677,Mary,Davis,Puerto Rico,Caguas,PR

In [4]:
df_customer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20652 entries, 0 to 20651
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Customer Id       20652 non-null  int64
 1   Customer Fname    20652 non-null  object
 2   Customer Lname    20644 non-null  object
 3   Customer Country  20652 non-null  object
 4   Customer City     20652 non-null  object
 5   Customer State    20652 non-null  object
dtypes: int64(1), object(5)
memory usage: 968.2+ KB

In [5]:
df_customer.shape

(20652, 6)

In [6]:
df_customer.isnull().sum()

Customer Id         0
Customer Fname      0
Customer Lname      8
Customer Country    0
Customer City       0
Customer State      0
dtype: int64

Order table

In [7]:
df_orders=pd.read_csv("Orders.csv")
df_orders

,Order Id,Customer Id,Product Card Id,order date (DateOrders),Order Status,Order Item Id,Order Item Quantity,Sales,Benefit per order,Order Item Discount,...,Order Profit Per Order,Customer Country,Customer City,Customer State,Order City,Order State,Order Region,Market,Latitude,Longitude
0,77202,20755,1360,1/31/2018 22:56,COMPLETE,180517,1,327.750000,91.250000,13.110000,...,91.250000,Puerto Rico,Caguas,PR,Bekasi,Java Occidental,Southeast Asia,Pacific Asia,18.251453,-66.037056
1,75939,19492,1360,1/13/2018 12:27,PENDING,179254,1,327.750000,-249.089996,16.389999,...,-249.089996,Puerto Rico,Caguas,PR,Bikaner,Rajastán,South Asia,Pacific Asia,18.279451,-66.037064
2,75938,19491,1360,1/13/2018 12:06,CLOSED,179253,1,327.750000,-247.779999,18.030001,...,-247.779999,EE. UU.,San Jose,CA,Bikaner,Rajastán,South Asia,Pacific Asia,37.292233,-121.881279
3,75937,19490,1360,1/13/2018 11:45,COMPLETE,179252,1,327.750000,22.860001,22.940001,...,22.860001,EE. UU.,Los Angeles,CA,Townsville,Queensland,Oceania,Pacific Asia,34.125946,-118.291016
4,75936,19489,1360,1/13/2018 11:24,PENDING_PAYMENT,179251,1,327.750000,134.210007,29.500000,...,134.210007,Puerto Rico,Caguas,PR,Townsville,Queensland,Oceania,Pacific Asia,18.253769,-66.037048
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180514,26043,1005,1004,1/16/2016 3:40,CLOSED,65177,1,399.980011,40.000000,0.000000,...,40.000000,EE. UU.,Brooklyn,NY,Shanghái,Shanghái,Eastern Asia,Pacific Asia,40.640930,-73.942711
180515,26037,9141,1004,1/16/2016 1:34,COMPLETE,65161,1,399.980011,-613.770019,4.000000,...,-613.770019,EE. UU.,Bakersfield,CA,Hirakata,Osaka,Eastern Asia,Pacific Asia,35.362545,-119.018700
180516,26024,291,1004,1/15/2016 21:00,PENDING,65129,1,399.980011,141.110001,8.000000,...,141.110001,EE. UU.,Bristol,CT,Adelaide,Australia del Sur,Oceania,Pacific Asia,41.629959,-72.967155
180517,26022,2813,1004,1/15/2016 20:18,PENDING_PAYMENT,65126,1,399.980011,186.229996,12.000000,...,186.229996,Puerto Rico,Caguas,PR,Adelaide,Australia del Sur,Oceania,Pacific Asia,18.213350,-66.370575
180518,26018,7547,1004,1/15/2016 18:54,PENDING_PAYMENT,65113,1,399.980011,168.949997,16.000000,...,168.949997,Puerto Rico,Caguas,PR,Nagercoil,Tamil Nadu,South Asia,Pacific Asia,18.290380,-66.370613

In [8]:
df_orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 24 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   Order Id                  180519 non-null  int64
 1   Customer Id               180519 non-null  int64
 2   Product Card Id           180519 non-null  int64
 3   order date (DateOrders)   180519 non-null  object
 4   Order Status              180519 non-null  object
 5   Order Item Id             180519 non-null  int64
 6   Order Item Quantity       180519 non-null  int64
 7   Sales                     180519 non-null  float64
 8   Benefit per order         180519 non-null  float64
 9   Order Item Discount       180519 non-null  float64
 10  Order Item Discount Rate  180519 non-null  float64
 11  Order Item Product Price  180519 non-null  float64
 12  Order Item Profit Ratio   180519 non-null  float64
 13  Order Item Total          180519 non-null  float64
 14  Order Profit Per Order    180519 non-null  float64
 15  Customer Country          180519 non-null  object
 16  Customer City             180519 non-null  object
 17  Customer State            180519 non-null  object
 18  Order City                180519 non-null  object
 19  Order State               180519 non-null  object
 20  Order Region              180519 non-null  object
 21  Market                    180519 non-null  object
 22  Latitude                  180519 non-null  float64
 23  Longitude                 180519 non-null  float64
dtypes: float64(10), int64(5), object(9)
memory usage: 33.1+ MB

In [9]:
# Handling with null values
df_orders.isnull().sum()

Order Id                    0
Customer Id                 0
Product Card Id             0
order date (DateOrders)     0
Order Status                0
Order Item Id               0
Order Item Quantity         0
Sales                       0
Benefit per order           0
Order Item Discount         0
Order Item Discount Rate    0
Order Item Product Price    0
Order Item Profit Ratio     0
Order Item Total            0
Order Profit Per Order      0
Customer Country            0
Customer City               0
Customer State              0
Order City                  0
Order State                 0
Order Region                0
Market                      0
Latitude                    0
Longitude                   0
dtype: int64

In [10]:
#Cleaning
df_orders.columns

Index(['Order Id', 'Customer Id', 'Product Card Id', 'order date (DateOrders)',
       'Order Status', 'Order Item Id', 'Order Item Quantity', 'Sales',
       'Benefit per order', 'Order Item Discount', 'Order Item Discount Rate',
       'Order Item Product Price', 'Order Item Profit Ratio',
       'Order Item Total', 'Order Profit Per Order', 'Customer Country',
       'Customer City', 'Customer State', 'Order City', 'Order State',
       'Order Region', 'Market', 'Latitude', 'Longitude'],
      dtype='object')

In [11]:
df_orders["Sales"]=df_orders["Sales"].round(2)

In [12]:
df_orders["Benefit per order"]=df_orders["Benefit per order"].round(2)

In [13]:
df_orders["Order Item Discount"]=df_orders["Order Item Discount"].round(2)

In [14]:
df_orders["Order Item Product Price"]=df_orders["Order Item Product Price"].round(2)
df_orders["Order Item Total"]=df_orders["Order Item Total"].round(2)
df_orders.drop(columns=['Latitude','Longitude','Order Item Profit Ratio','Order Profit Per Order'],inplace=True)
df_orders=df_orders.rename(columns={"order date (DateOrders)":"order date"})
df_orders=df_orders.rename(columns={"Order Item Product Price":"price per item"})
df_orders=df_orders.rename(columns={"Sales":"Total Sales"})

In [15]:
df_orders

,Order Id,Customer Id,Product Card Id,order date,Order Status,Order Item Id,Order Item Quantity,Total Sales,Benefit per order,Order Item Discount,Order Item Discount Rate,price per item,Order Item Total,Customer Country,Customer City,Customer State,Order City,Order State,Order Region,Market
0,77202,20755,1360,1/31/2018 22:56,COMPLETE,180517,1,327.75,91.25,13.11,0.04,327.75,314.64,Puerto Rico,Caguas,PR,Bekasi,Java Occidental,Southeast Asia,Pacific Asia
1,75939,19492,1360,1/13/2018 12:27,PENDING,179254,1,327.75,-249.09,16.39,0.05,327.75,311.36,Puerto Rico,Caguas,PR,Bikaner,Rajastán,South Asia,Pacific Asia
2,75938,19491,1360,1/13/2018 12:06,CLOSED,179253,1,327.75,-247.78,18.03,0.06,327.75,309.72,EE. UU.,San Jose,CA,Bikaner,Rajastán,South Asia,Pacific Asia
3,75937,19490,1360,1/13/2018 11:45,COMPLETE,179252,1,327.75,22.86,22.94,0.07,327.75,304.81,EE. UU.,Los Angeles,CA,Townsville,Queensland,Oceania,Pacific Asia
4,75936,19489,1360,1/13/2018 11:24,PENDING_PAYMENT,179251,1,327.75,134.21,29.50,0.09,327.75,298.25,Puerto Rico,Caguas,PR,Townsville,Queensland,Oceania,Pacific Asia
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180514,26043,1005,1004,1/16/2016 3:40,CLOSED,65177,1,399.98,40.00,0.00,0.00,399.98,399.98,EE. UU.,Brooklyn,NY,Shanghái,Shanghái,Eastern Asia,Pacific Asia
180515,26037,9141,1004,1/16/2016 1:34,COMPLETE,65161,1,399.98,-613.77,4.00,0.01,399.98,395.98,EE. UU.,Bakersfield,CA,Hirakata,Osaka,Eastern Asia,Pacific Asia
180516,26024,291,1004,1/15/2016 21:00,PENDING,65129,1,399.98,141.11,8.00,0.02,399.98,391.98,EE. UU.,Bristol,CT,Adelaide,Australia del Sur,Oceania,Pacific Asia
180517,26022,2813,1004,1/15/2016 20:18,PENDING_PAYMENT,65126,1,399.98,186.23,12.00,0.03,399.98,387.98,Puerto Rico,Caguas,PR,Adelaide,Australia del Sur,Oceania,Pacific Asia
180518,26018,7547,1004,1/15/2016 18:54,PENDING_PAYMENT,65113,1,399.98,168.95,16.00,0.04,399.98,383.98,Puerto Rico,Caguas,PR,Nagercoil,Tamil Nadu,South Asia,Pacific Asia

In [16]:
# Convert mixed date formats
df_orders["order date"] = pd.to_datetime(
    df_orders["order date"],
    format="mixed", # take all dates in one format automaticaly
    errors="raise"
)

In [17]:
# Remove the time part
df_orders["order date"] = df_orders["order date"].dt.date

# Check null values
print(df_orders["order date"].isnull().sum())

0

In [18]:
df_orders.isnull().sum()

Order Id                    0
Customer Id                 0
Product Card Id             0
order date                  0
Order Status                0
Order Item Id               0
Order Item Quantity         0
Total Sales                 0
Benefit per order           0
Order Item Discount         0
Order Item Discount Rate    0
price per item              0
Order Item Total            0
Customer Country            0
Customer City               0
Customer State              0
Order City                  0
Order State                 0
Order Region                0
Market                      0
dtype: int64

In [19]:
df_orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 20 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   Order Id                  180519 non-null  int64
 1   Customer Id               180519 non-null  int64
 2   Product Card Id           180519 non-null  int64
 3   order date                180519 non-null  object
 4   Order Status              180519 non-null  object
 5   Order Item Id             180519 non-null  int64
 6   Order Item Quantity       180519 non-null  int64
 7   Total Sales               180519 non-null  float64
 8   Benefit per order         180519 non-null  float64
 9   Order Item Discount       180519 non-null  float64
 10  Order Item Discount Rate  180519 non-null  float64
 11  price per item            180519 non-null  float64
 12  Order Item Total          180519 non-null  float64
 13  Customer Country          180519 non-null  object
 14  Customer City             180519 non-null  object
 15  Customer State            180519 non-null  object
 16  Order City                180519 non-null  object
 17  Order State               180519 non-null  object
 18  Order Region              180519 non-null  object
 19  Market                    180519 non-null  object
dtypes: float64(6), int64(5), object(9)
memory usage: 27.5+ MB

In [20]:
df_orders

,Order Id,Customer Id,Product Card Id,order date,Order Status,Order Item Id,Order Item Quantity,Total Sales,Benefit per order,Order Item Discount,Order Item Discount Rate,price per item,Order Item Total,Customer Country,Customer City,Customer State,Order City,Order State,Order Region,Market
0,77202,20755,1360,2018-01-31,COMPLETE,180517,1,327.75,91.25,13.11,0.04,327.75,314.64,Puerto Rico,Caguas,PR,Bekasi,Java Occidental,Southeast Asia,Pacific Asia
1,75939,19492,1360,2018-01-13,PENDING,179254,1,327.75,-249.09,16.39,0.05,327.75,311.36,Puerto Rico,Caguas,PR,Bikaner,Rajastán,South Asia,Pacific Asia
2,75938,19491,1360,2018-01-13,CLOSED,179253,1,327.75,-247.78,18.03,0.06,327.75,309.72,EE. UU.,San Jose,CA,Bikaner,Rajastán,South Asia,Pacific Asia
3,75937,19490,1360,2018-01-13,COMPLETE,179252,1,327.75,22.86,22.94,0.07,327.75,304.81,EE. UU.,Los Angeles,CA,Townsville,Queensland,Oceania,Pacific Asia
4,75936,19489,1360,2018-01-13,PENDING_PAYMENT,179251,1,327.75,134.21,29.50,0.09,327.75,298.25,Puerto Rico,Caguas,PR,Townsville,Queensland,Oceania,Pacific Asia
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180514,26043,1005,1004,2016-01-16,CLOSED,65177,1,399.98,40.00,0.00,0.00,399.98,399.98,EE. UU.,Brooklyn,NY,Shanghái,Shanghái,Eastern Asia,Pacific Asia
180515,26037,9141,1004,2016-01-16,COMPLETE,65161,1,399.98,-613.77,4.00,0.01,399.98,395.98,EE. UU.,Bakersfield,CA,Hirakata,Osaka,Eastern Asia,Pacific Asia
180516,26024,291,1004,2016-01-15,PENDING,65129,1,399.98,141.11,8.00,0.02,399.98,391.98,EE. UU.,Bristol,CT,Adelaide,Australia del Sur,Oceania,Pacific Asia
180517,26022,2813,1004,2016-01-15,PENDING_PAYMENT,65126,1,399.98,186.23,12.00,0.03,399.98,387.98,Puerto Rico,Caguas,PR,Adelaide,Australia del Sur,Oceania,Pacific Asia
180518,26018,7547,1004,2016-01-15,PENDING_PAYMENT,65113,1,399.98,168.95,16.00,0.04,399.98,383.98,Puerto Rico,Caguas,PR,Nagercoil,Tamil Nadu,South Asia,Pacific Asia

In [21]:
#Category Table
df_category=pd.read_csv("category.csv")
df_category

,Product Category Id,Category Name,Department Id,Department Name
0,73,Sporting Goods,2,Fitness
1,17,Cleats,4,Apparel
2,29,Shop By Sport,5,Golf
3,24,Women's Apparel,5,Golf
4,13,Electronics,3,Footwear
5,12,Boxing & MMA,3,Footwear
6,9,Cardio Equipment,3,Footwear
7,41,Trade-In,6,Outdoors
8,37,Electronics,6,Outdoors
9,38,Kids' Golf Clubs,6,Outdoors
10,44,Hunting & Shooting,7,Fan Shop
11,3,Baseball & Softball,2,Fitness
12,18,Men's Footwear,4,Apparel
13,43,Camping & Hiking,7,Fan Shop
14,65,Consumer Electronics,10,Technology
15,62,Cameras,10,Technology
16,64,Computers,10,Technology
17,4,Basketball,2,Fitness
18,2,Soccer,2,Fitness
19,26,Girls' Apparel,5,Golf
20,40,Accessories,6,Outdoors
21,76,Women's Clothing,4,Apparel
22,66,Crafts,4,Apparel
23,70,Men's Clothing,4,Apparel
24,6,Tennis & Racquet,2,Fitness
25,11,Fitness Accessories,3,Footwear
26,16,As Seen on TV!,3,Footwear
27,36,Golf Balls,6,Outdoors
28,10,Strength Training,3,Footwear
29,63,Children's Clothing,4,Apparel
30,5,Lacrosse,2,Fitness
31,60,Baby,4,Apparel
32,45,Fishing,7,Fan Shop
33,59,Books,8,Book Shop
34,67,DVDs,9,Discs Shop
35,61,CDs,9,Discs Shop
36,68,Garden,6,Outdoors
37,7,Hockey,2,Fitness
38,72,Pet Supplies,11,Pet Shop
39,69,Health and Beauty,12,Health and Beauty
40,71,Music,9,Discs Shop
41,75,Video Games,9,Discs Shop
42,35,Golf Gloves,6,Outdoors
43,34,Golf Bags & Carts,6,Outdoors
44,33,Golf Shoes,6,Outdoors
45,32,Golf Apparel,6,Outdoors
46,31,Women's Golf Clubs,6,Outdoors
47,30,Men's Golf Clubs,6,Outdoors
48,74,Toys,7,Fan Shop
49,48,Water Sports,7,Fan Shop
50,46,Indoor/Outdoor Games,7,Fan Shop

In [22]:
df_category.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Product Category Id  51 non-null     int64
 1   Category Name        51 non-null     object
 2   Department Id        51 non-null     int64
 3   Department Name      51 non-null     object
dtypes: int64(2), object(2)
memory usage: 1.7+ KB

In [23]:
df_category.shape

(51, 4)

In [24]:
df_category.isnull().sum()

Product Category Id    0
Category Name          0
Department Id          0
Department Name        0
dtype: int64

In [25]:
#Product Table
df_product=pd.read_csv("product.csv")
df_product

,Product Card Id,Product Name,Product Category Id,Category Name,Department Id,Department Name,Product Price
0,1360,Smart watch,73,Sporting Goods,2,Fitness,327.750000
1,365,Perfect Fitness Perfect Rip Deck,17,Cleats,4,Apparel,59.990002
2,627,Under Armour Girls' Toddler Spine Surge Runni,29,Shop By Sport,5,Golf,39.990002
3,502,Nike Men's Dri-FIT Victory Golf Polo,24,Women's Apparel,5,Golf,50.000000
4,278,Under Armour Men's Compression EV SL Slide,13,Electronics,3,Footwear,44.990002
...,...,...,...,...,...,...,...
113,646,Merrell Women's Grassbow Sport Hiking Shoe,30,Men's Golf Clubs,6,Outdoors,99.989998
114,1361,Toys,74,Toys,7,Fan Shop,11.540000
115,1073,Pelican Sunstream 100 Kayak,48,Water Sports,7,Fan Shop,199.990005
116,1059,Pelican Maverick 100X Kayak,48,Water Sports,7,Fan Shop,349.989990
117,1014,O'Brien Men's Neoprene Life Vest,46,Indoor/Outdoor Games,7,Fan Shop,49.980000

In [26]:
df_product.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 118 entries, 0 to 117
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Product Card Id      118 non-null    int64
 1   Product Name         118 non-null    object
 2   Product Category Id  118 non-null    int64
 3   Category Name        118 non-null    object
 4   Department Id        118 non-null    int64
 5   Department Name      118 non-null    object
 6   Product Price        118 non-null    float64
dtypes: float64(1), int64(3), object(3)
memory usage: 6.6+ KB

In [27]:
df_product.isnull().sum()

Product Card Id        0
Product Name           0
Product Category Id    0
Category Name          0
Department Id          0
Department Name        0
Product Price          0
dtype: int64

In [28]:
df_product["Product Price"]=df_product["Product Price"].round(2)

In [29]:
df_product

,Product Card Id,Product Name,Product Category Id,Category Name,Department Id,Department Name,Product Price
0,1360,Smart watch,73,Sporting Goods,2,Fitness,327.75
1,365,Perfect Fitness Perfect Rip Deck,17,Cleats,4,Apparel,59.99
2,627,Under Armour Girls' Toddler Spine Surge Runni,29,Shop By Sport,5,Golf,39.99
3,502,Nike Men's Dri-FIT Victory Golf Polo,24,Women's Apparel,5,Golf,50.00
4,278,Under Armour Men's Compression EV SL Slide,13,Electronics,3,Footwear,44.99
...,...,...,...,...,...,...,...
113,646,Merrell Women's Grassbow Sport Hiking Shoe,30,Men's Golf Clubs,6,Outdoors,99.99
114,1361,Toys,74,Toys,7,Fan Shop,11.54
115,1073,Pelican Sunstream 100 Kayak,48,Water Sports,7,Fan Shop,199.99
116,1059,Pelican Maverick 100X Kayak,48,Water Sports,7,Fan Shop,349.99
117,1014,O'Brien Men's Neoprene Life Vest,46,Indoor/Outdoor Games,7,Fan Shop,49.98

In [30]:
#Shipping
df_shipping=pd.read_csv("shiping.csv")
df_shipping

,Order Id,Delivery Status,Shipping Mode,Days for shipping (real),Days for shipment (scheduled),Late_delivery_risk
0,77202,Advance shipping,Standard Class,3,4,0
1,75939,Late delivery,Standard Class,5,4,1
2,75938,Shipping on time,Standard Class,4,4,0
3,75937,Advance shipping,Standard Class,3,4,0
4,75936,Advance shipping,Standard Class,2,4,0
...,...,...,...,...,...,...
180514,26043,Shipping on time,Standard Class,4,4,0
180515,26037,Late delivery,Second Class,3,2,1
180516,26024,Late delivery,Standard Class,5,4,1
180517,26022,Advance shipping,Standard Class,3,4,0
180518,26018,Shipping on time,Standard Class,4,4,0

In [31]:
df_shipping.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 6 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Order Id                       180519 non-null  int64
 1   Delivery Status                180519 non-null  object
 2   Shipping Mode                  180519 non-null  object
 3   Days for shipping (real)       180519 non-null  int64
 4   Days for shipment (scheduled)  180519 non-null  int64
 5   Late_delivery_risk             180519 non-null  int64
dtypes: int64(4), object(2)
memory usage: 8.3+ MB

In [32]:
df_shipping.isnull().sum()

Order Id                         0
Delivery Status                  0
Shipping Mode                    0
Days for shipping (real)         0
Days for shipment (scheduled)    0
Late_delivery_risk               0
dtype: int64

In [36]:
df_category.to_csv("category_cleaned.csv", index=False)

df_customer.to_csv("customers_cleaned.csv", index=False)

df_orders.to_csv("orders_cleaned.csv", index=False)

df_product.to_csv("products_cleaned.csv", index=False)
df_shipping.to_csv("shiping_cleaned.csv", index=False)